### ISSUE TITLE
[BUG] Unable to sign in local mode

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-windows#1242]
**Describe the bug**
It is impossible to get a vaild signature for tx broadcast on local mode with neiter iOS or android joining.
**To Reproduce**
1. initiate tx on windows
2. change to local mode
3. join with devices

**Expected behavior**
Able to use local mode properly

**Screenshots**
![Image](https://github.com/user-attachments/assets/5bebda1c-92a2-40c4-971a-a1797cfcec0d)

![Image](https://github.com/user-attachments/assets/1f8bace2-5416-43b9-bc1b-f2fc456775e0)

**Desktop (please complete the following information):**
 - Version 16

**Comment by johnnyluo** [comment]
This should be fixed in #1278 , keep in mind , on MacOS , this will not work , as the mDNS service vultisig provide will conflict with mDNSResponder comes from MacOS itself , obviously mDNSResponder will take priority

**Comment by realpaaao** [comment]
@johnnyluo I am still not able to sign. Though now it does not crash anymore but the joining devices will be stuck in `Discovering mediator device`

**Comment by johnnyluo** [comment]
When you are working on windows OS?  is mDNS supported on your network?
